# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
            version: 12;
        
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name: Creating build
        run: yarn build
    
      - name: installing surge  
        run: npm install -g surge


      - name: deploying on surge
        run: surge ./build https://timerappbyafaq.surge.sh/--token ${{secrets.SURGE_TOKEN}}
